/** Catálogo gama perro — fuente: product-marketing.md + customdiet.es */
export const PRODUCTS = {
  'angus-beef': {
    id: 'angus-beef',
    name: 'Angus Beef',
    slug: 'custom-diet-angus-beef',
    url: 'https://customdiet.es/product/custom-diet-angus-beef/',
    tags: ['grain-free', 'energy', 'heart'],
    proteins: ['ternera', 'pollo'],
    em: 4375,
    role: 'desayuno',
    description:
      'La receta más energética de la gama adulto. Ideal para perros activos que necesitan densidad calórica y proteína reforzada.',
    image: null,
  },
  rabbit: {
    id: 'rabbit',
    name: 'Rabbit',
    slug: 'custom-diet-rabbit',
    url: 'https://customdiet.es/product/custom-diet-rabbit/',
    tags: ['grain-free', 'energy', 'heart'],
    proteins: ['conejo', 'pato'],
    em: 3780,
    role: 'comida',
    description:
      'Proteína poco habitual, perfecta para introducir variedad. Equilibrio entre energía y digestibilidad.',
    image: null,
  },
  lamb: {
    id: 'lamb',
    name: 'Lamb',
    slug: 'custom-diet-lamb',
    url: 'https://customdiet.es/product/custom-diet-lamb/',
    tags: ['grain-free', 'energy', 'heart'],
    proteins: ['cordero', 'pato'],
    em: 3780,
    role: 'comida',
    description:
      'Alternativa nutritiva al conejo para rotar proteínas sin transición. Buena opción de comida intermedia.',
    image: null,
  },
  salmon: {
    id: 'salmon',
    name: 'Salmon',
    slug: 'custom-diet-salmon',
    url: 'https://customdiet.es/product/custom-diet-salmon/',
    tags: ['grain-free', 'monoprotein', 'hipoalergenico'],
    proteins: ['salmon'],
    em: 2935,
    role: 'cena',
    description:
      'Monoproteína real de salmón. Ligera, hipoalergénica y rica en omega 3 para piel, pelaje e inmunidad.',
    image: null,
  },
  turkey: {
    id: 'turkey',
    name: 'Turkey',
    slug: 'custom-diet-turkey',
    url: 'https://customdiet.es/product/custom-diet-turkey/',
    tags: ['grain-free', 'monoprotein', 'hipoalergenico'],
    proteins: ['pavo'],
    containsSalmonOil: true,
    em: 2780,
    role: 'cena',
    description:
      'La receta más ligera de la gama. Monoproteína de pavo, ideal como cena o para perros sedentarios.',
    image: null,
  },
  tuna: {
    id: 'tuna',
    name: 'Tuna',
    slug: 'custom-diet-tuna',
    url: 'https://customdiet.es/product/custom-diet-tuna/',
    tags: ['grain-free', 'monoprotein', 'hipoalergenico'],
    proteins: ['atun', 'anchoveta', 'melva', 'albacora'],
    em: 2935,
    role: 'cena',
    description:
      'Mezcla de pescados azules con omega 3. Ligera y digestiva; aporta variedad marina a la rotación.',
    image: null,
  },
  'angus-beef-puppy': {
    id: 'angus-beef-puppy',
    name: 'Angus Beef Puppy',
    slug: 'custom-diet-angus-beef-puppy',
    url: 'https://customdiet.es/product/custom-diet-angus-beef-puppy/',
    tags: ['grain-free', 'puppy', 'epa-dha'],
    proteins: ['ternera', 'salmon', 'pollo'],
    em: 4415,
    role: 'base',
    description:
      'Formulada para cachorros con EPA/DHA y calcio reforzado. Alta densidad calórica para el crecimiento.',
    image: null,
  },
  'chicken-mini': {
    id: 'chicken-mini',
    name: 'Chicken Mini',
    slug: 'custom-diet-chicken-mini',
    url: 'https://customdiet.es/product/custom-diet-chicken-mini/',
    tags: ['low-grain', 'mini', 'energy'],
    proteins: ['pollo'],
    em: 3140,
    role: 'comida',
    description:
      'Pensada para razas pequeñas. Proteína de pollo con formato y nutrientes adaptados al mini.',
    image: null,
  },
  'salmon-mini': {
    id: 'salmon-mini',
    name: 'Salmon Mini',
    slug: 'custom-diet-salmon-mini',
    url: 'https://customdiet.es/product/custom-diet-salmon-mini/',
    tags: ['low-grain', 'mini', 'skin-coat'],
    proteins: ['salmon', 'pollo'],
    containsChicken: true,
    em: 3740,
    role: 'comida',
    description:
      'Cuidado de piel y pelaje para mini. ⚠️ Contiene pollo además de salmón — revisar si hay alergia.',
    image: null,
  },
  gastrointestinal: {
    id: 'gastrointestinal',
    name: 'Gastrointestinal',
    slug: 'custom-diet-gastrointestinal',
    url: 'https://customdiet.es/product/custom-diet-gastrointestinal/',
    tags: ['vet', 'digestivo'],
    proteins: ['pescado-blanco-hidrolizado', 'higado-ave', 'huevo'],
    isVet: true,
    role: 'base',
    description:
      'Línea veterinaria con proteína hidrolizada, MOS/FOS y botánicos digestivos. Consulta con tu veterinario.',
    image: null,
  },
  obesity: {
    id: 'obesity',
    name: 'Obesity',
    slug: 'custom-diet-obesity',
    url: 'https://customdiet.es/product/custom-diet-obesity/',
    tags: ['vet', 'control-peso'],
    proteins: ['pavo-hidrolizado', 'higado-ave', 'huevo', 'krill'],
    isVet: true,
    em: 2614,
    role: 'base',
    description:
      'Control de peso con L-carnitina y alta fibra (12%). La fórmula más ligera de toda la gama.',
    image: null,
  },
};

export const PROTEIN_ALLERGIES = [
  { id: 'pollo', label: 'Pollo' },
  { id: 'ternera', label: 'Ternera / vacuno' },
  { id: 'pescado', label: 'Pescado (cualquier especie)' },
  { id: 'conejo', label: 'Conejo' },
  { id: 'cordero', label: 'Cordero' },
  { id: 'pato', label: 'Pato' },
  { id: 'desconocida', label: 'No lo sé / sin confirmar' },
];
